version: 2
jobs:
  build:
    working_directory: ~/wkt-geom
    docker:
      - image: circleci/ruby:2.4.4
    steps:
      - checkout
      - restore-cache:
          keys:
            - stack{{checksum "stack.yaml"}}
      - restore-cache:
          keys:
            - stack{{checksum "wkt-geom.cabal"}}{{checksum "stack.yaml"}}
      - run:
          name: install
          command: |
            rm -rf ~/wkt-geom/.stack-work/downloaded
            wget https://github.com/commercialhaskell/stack/releases/download/v1.7.1/stack-1.7.1-linux-x86_64.tar.gz -O /tmp/stack.tar.gz
            mkdir /tmp/stack/
            tar -xvzf /tmp/stack.tar.gz -C /tmp/stack/
            sudo mv /tmp/stack/stack-1.7.1-linux-x86_64/stack /usr/local/bin/stack
      - run:
          name: pre
          no_output_timeout: 60m
          command: |
            stack setup --stack-yaml stack.yaml --no-terminal -j2
            stack build --stack-yaml stack.yaml --no-system-ghc --only-configure --no-terminal -j2
      - run:
          name: compile
          no_output_timeout: 60m
          command: |
            stack build --stack-yaml stack.yaml --no-terminal -j2
      - run:
          name: test
          no_output_timeout: 60m
          command: |
            stack test --stack-yaml stack.yaml --no-terminal -j2
      - save-cache:
          key: stack{{checksum "stack.yaml"}}
          paths:
            - "~/.stack"
      - save-cache:
          key: stack{{checksum "wkt-geom.cabal"}}{{checksum "stack.yaml"}}
          paths:
            - "~/wkt-geom/.stack-work"